import type { DatabaseConnection } from '../types.js';
import { phAt, toBoolean, toIso } from '../db/rows.js';
import type { UserRole } from './tokenRepository.js';

/**
 * users 表 repository。
 *
 * user_uid 分配策略（schema/sqlite/0001_init.sql 头注）：
 * - PostgreSQL：`GENERATED BY DEFAULT AS IDENTITY`，插入省略该列由序列分配
 * - SQLite：应用层在插入事务内 MAX(user_uid)+1（单写者场景）
 * 两种方言下该方法都必须在调用方事务内执行（IdentityService 负责）。
 */

/**
 * 用户名模式（0003）。
 *
 * - 'single'：单用户名。沿用 Minecraft 正版的 30 天改名冷却，账号只能有 1 个
 *   active 角色；其余角色只能是 'reserved'（预留口），且**当前不可用**。
 * - 'multi' ：多用户名。无改名冷却，活跃 + 预留合计上限 10 个。
 *
 * 强调「当前不可用」是因为预留角色的名字仍被占住（防抢注）：用户必须等满冷却
 * 才能把预留口里的角色搬回 active。见 ProfileRepository 与 IdentityService。
 */
export type ProfileMode = 'single' | 'multi';

export interface UserRow {
  id: string;
  userUid: number;
  email: string;
  passwordHash: string;
  role: UserRole;
  isActive: boolean;
  emailVerified: boolean;
  bannedUntil: string | null;
  banPermanent: boolean;
  banReason: string | null;
  /**
   * 本次封禁的下达时刻（0005）。非空 = 当前处于封禁中；解封时清空。
   * 管理后台「封禁趋势」按这一列分日聚合。
   */
  bannedAt: string | null;
  createdAt: string;
  updatedAt: string;
  lastLoginAt: string | null;
  /** 非空 = 已注销，处于可恢复宽限期（见 0002_account_lifecycle.sql） */
  deletedAt: string | null;
  /** 非空 = 宽限期已过、个人数据已清除；行保留以占住 user_uid（UID 永不复用） */
  purgedAt: string | null;
  // ---- 0003：用户名模式 ----
  profileMode: ProfileMode;
  /**
   * 模式选择的完成时刻。NULL = **待选择**：该账号在迁移时角色数 > 1，
   * 下次登录必须选一个保留 ID 才能继续（选完写非 NULL，不再弹窗）。
   */
  profileModeDecidedAt: string | null;
  /** 模式切换的计时基准（切换动作与具体角色无关，所以基准放 users 而非 profiles） */
  modeChangedAt: string | null;
  // ---- 0003：备用邮箱（兜底）----
  backupEmail: string | null;
  backupEmailVerified: boolean;
  backupEmailVerifiedAt: string | null;
}

export interface NewUserRow {
  /** 应用层生成（uuidv4 小写带连字符） */
  id: string;
  /** 必须已规范化为小写 */
  email: string;
  passwordHash: string;
  role: UserRole;
  now: Date;
  /**
   * 首次模式决定的时刻。注册流程角色数为 0，视为已决定，应传 `now`；
   * 传 `null`/省略则写 NULL = 待选择（只可能出现在数据修补场景，正常注册不会）。
   */
  profileModeDecidedAt?: Date | null;
  /**
   * 注册时的初始用户名模式。省略写列默认 'single'；
   * 全局模式为 multi 的站点应显式传入（register 从全局设置读取）。
   */
  profileMode?: 'single' | 'multi';
}

const USER_COLUMNS =
  'id, user_uid, email, password_hash, role, is_active, email_verified, ' +
  'banned_until, ban_permanent, ban_reason, banned_at, created_at, updated_at, last_login_at, ' +
  'deleted_at, purged_at, profile_mode, profile_mode_decided_at, mode_changed_at, ' +
  'backup_email, backup_email_verified, backup_email_verified_at';

function mapUserRow(raw: Record<string, unknown>): UserRow {
  return {
    id: raw['id'] as string,
    userUid: Number(raw['user_uid']),
    email: raw['email'] as string,
    passwordHash: raw['password_hash'] as string,
    role: raw['role'] as UserRole,
    isActive: toBoolean(raw['is_active']),
    emailVerified: toBoolean(raw['email_verified']),
    bannedUntil: toIso(raw['banned_until']),
    banPermanent: toBoolean(raw['ban_permanent']),
    banReason: (raw['ban_reason'] as string | null) ?? null,
    bannedAt: toIso(raw['banned_at']),
    createdAt: toIso(raw['created_at'])!,
    updatedAt: toIso(raw['updated_at'])!,
    lastLoginAt: toIso(raw['last_login_at']),
    deletedAt: toIso(raw['deleted_at']),
    purgedAt: toIso(raw['purged_at']),
    profileMode: (raw['profile_mode'] as ProfileMode | null) ?? 'single',
    profileModeDecidedAt: toIso(raw['profile_mode_decided_at']),
    modeChangedAt: toIso(raw['mode_changed_at']),
    backupEmail: (raw['backup_email'] as string | null) ?? null,
    backupEmailVerified: toBoolean(raw['backup_email_verified']),
    backupEmailVerifiedAt: toIso(raw['backup_email_verified_at']),
  };
}

export class UserRepository {
  constructor(private readonly db: DatabaseConnection) {}

  /** 插入用户，返回分配到的 user_uid */
  async insert(user: NewUserRow): Promise<number> {
    const now = user.now.toISOString();
    // 新账号此刻角色数为 0，视作模式已决定；显式传 NULL 才是「待选择」
    const decidedAt =
      user.profileModeDecidedAt === undefined
        ? now
        : (user.profileModeDecidedAt?.toISOString() ?? null);

    if (this.db.dialect === 'postgres') {
      const rows = await this.db.query<Record<string, unknown>>(
        `INSERT INTO users (id, email, password_hash, role, is_active,
           email_verified, ban_permanent, profile_mode, profile_mode_decided_at, created_at, updated_at)
         VALUES ($1, $2, $3, $4, TRUE, FALSE, FALSE, $5, $6, $7, $7)
         RETURNING user_uid`,
        [user.id, user.email, user.passwordHash, user.role, user.profileMode ?? 'single', decidedAt, now],
      );
      return Number(rows[0]!['user_uid']);
    }

    // SQLite：同一事务内 MAX+1（见文件头注）
    const uidRows = await this.db.query<Record<string, unknown>>(
      'SELECT COALESCE(MAX(user_uid), 0) + 1 AS next_uid FROM users',
    );
    const userUid = Number(uidRows[0]!['next_uid']);
    await this.db.run(
      `INSERT INTO users (id, user_uid, email, password_hash, role, is_active,
         email_verified, ban_permanent, profile_mode, profile_mode_decided_at, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, 1, 0, 0, ?, ?, ?, ?)`,
      [
        user.id,
        userUid,
        user.email,
        user.passwordHash,
        user.role,
        user.profileMode ?? 'single',
        decidedAt,
        now,
        now,
      ],
    );
    return userUid;
  }

  async findByEmail(email: string): Promise<UserRow | null> {
    // email 唯一索引按 lower(email) 建立应用层不再依赖大小写形式
    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users WHERE lower(email) = ${phAt(this.db.dialect, 0)}`,
      [email.toLowerCase()],
    );
    return rows[0] ? mapUserRow(rows[0]) : null;
  }

  async findById(id: string): Promise<UserRow | null> {
    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users WHERE id = ${phAt(this.db.dialect, 0)}`,
      [id],
    );
    return rows[0] ? mapUserRow(rows[0]) : null;
  }

  async updateLastLogin(userId: string, at: Date): Promise<void> {
    // 注意：占位符下标不可重复（SQLite 每个 ? 都需要绑定值，PG 的 $n 重复只算一个）
    await this.db.run(
      `UPDATE users SET last_login_at = ${phAt(this.db.dialect, 0)},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [at.toISOString(), at.toISOString(), userId],
    );
  }

  /** 管理员用户列表（email 模糊搜索 + 分页），按 user_uid 升序 */
  async listUsers(options: {
    offset: number;
    limit: number;
    search?: string;
  }): Promise<{ rows: UserRow[]; total: number }> {
    const { offset, limit, search } = options;
    const like = search ? `%${search.toLowerCase()}%` : null;
    const searchClause = like
      ? ` WHERE lower(email) LIKE ${phAt(this.db.dialect, 0)}`
      : '';

    const countRows = await this.db.query<Record<string, unknown>>(
      `SELECT COUNT(*) AS total FROM users${searchClause}`,
      like ? [like] : [],
    );
    const total = Number(countRows[0]!['total']);

    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users${searchClause}
       ORDER BY user_uid ASC
       LIMIT ${phAt(this.db.dialect, like ? 1 : 0)}
       OFFSET ${phAt(this.db.dialect, like ? 2 : 1)}`,
      like ? [like, limit, offset] : [limit, offset],
    );
    return { rows: rows.map(mapUserRow), total };
  }

  /** 管理员更新用户管理字段（角色/封禁/激活），仅写传入的字段 */
  async updateAdminFields(
    userId: string,
    fields: {
      role?: UserRole;
      isActive?: boolean;
      bannedUntil?: string | null;
      banPermanent?: boolean;
      banReason?: string | null;
      /** 本次封禁下达时刻；解封时传 null 清空（0005） */
      bannedAt?: string | null;
    },
    now: Date,
  ): Promise<void> {
    const sets: string[] = [];
    const values: unknown[] = [];
    let i = 0;
    if (fields.role !== undefined) {
      sets.push(`role = ${phAt(this.db.dialect, i++)}`);
      values.push(fields.role);
    }
    if (fields.isActive !== undefined) {
      sets.push(`is_active = ${phAt(this.db.dialect, i++)}`);
      values.push(this.db.dialect === 'postgres' ? fields.isActive : fields.isActive ? 1 : 0);
    }
    if (fields.bannedAt !== undefined) {
      // PG 的时间列绑参需显式转换，否则 pg 会把字符串当 text 传给 timestamptz
      const ph = phAt(this.db.dialect, i++);
      sets.push(
        `banned_at = ${this.db.dialect === 'postgres' ? `${ph}::timestamptz` : ph}`,
      );
      values.push(fields.bannedAt);
    }
    if (fields.bannedUntil !== undefined) {
      sets.push(`banned_until = ${phAt(this.db.dialect, i++)}`);
      values.push(fields.bannedUntil);
    }
    if (fields.banPermanent !== undefined) {
      sets.push(`ban_permanent = ${phAt(this.db.dialect, i++)}`);
      values.push(this.db.dialect === 'postgres' ? fields.banPermanent : fields.banPermanent ? 1 : 0);
    }
    if (fields.banReason !== undefined) {
      sets.push(`ban_reason = ${phAt(this.db.dialect, i++)}`);
      values.push(fields.banReason);
    }
    sets.push(`updated_at = ${phAt(this.db.dialect, i++)}`);
    values.push(now.toISOString());
    values.push(userId);

    await this.db.run(
      `UPDATE users SET ${sets.join(', ')} WHERE id = ${phAt(this.db.dialect, i++)}`,
      values,
    );
  }

  // ---- 账号生命周期（改密 / 注销 / 恢复 / 到期清除）----

  async updatePassword(
    userId: string,
    passwordHash: string,
    at: Date,
  ): Promise<void> {
    await this.db.run(
      `UPDATE users SET password_hash = ${phAt(this.db.dialect, 0)},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [passwordHash, at.toISOString(), userId],
    );
  }

  /**
   * 标记邮箱已验证（P5）。幂等：重复调用不改变结果。
   *
   * 由两条路径触发 —— 用户点邮件里的验证链接，或管理员在用户管理页手动放行
   * （用户收不到信时的兜底手段）。
   */
  async setEmailVerified(
    userId: string,
    verified: boolean,
    at: Date,
  ): Promise<void> {
    await this.db.run(
      `UPDATE users SET email_verified = ${phAt(this.db.dialect, 0)},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [
        this.db.dialect === 'postgres' ? verified : verified ? 1 : 0,
        at.toISOString(),
        userId,
      ],
    );
  }

  /** 注销：置 deleted_at，进入可恢复宽限期 */
  async markDeleted(userId: string, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET deleted_at = ${phAt(this.db.dialect, 0)},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [at.toISOString(), at.toISOString(), userId],
    );
  }

  /** 恢复：清 deleted_at，账号回到正常状态 */
  async clearDeleted(userId: string, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET deleted_at = NULL,
         updated_at = ${phAt(this.db.dialect, 0)}
       WHERE id = ${phAt(this.db.dialect, 1)}`,
      [at.toISOString(), userId],
    );
  }

  /**
   * 宽限期到期清除：邮箱改墓碑值（释放原邮箱给新注册）、密码清空、停用，
   * 并写 purged_at。**行本身保留**——SQLite 的 user_uid 由 MAX(uid)+1 分配，
   * 删行会导致 UID 被后续注册复用，而 UID 要求永不复用。
   *
   * 备用邮箱一并清空：它与主邮箱同为「可被占用的全局唯一地址」，
   * 留着一个已清除账号占住别人想注册的地址，比墓碑主邮箱更莫名其妙
   * （主邮箱有墓碑值可供人工追溯，备用邮箱没有这种用途）。
   */
  async purgeUser(
    userId: string,
    tombstoneEmail: string,
    at: Date,
  ): Promise<void> {
    await this.db.run(
      `UPDATE users SET email = ${phAt(this.db.dialect, 0)},
         password_hash = '',
         is_active = ${this.db.dialect === 'postgres' ? 'FALSE' : '0'},
         deleted_at = NULL,
         purged_at = ${phAt(this.db.dialect, 1)},
         backup_email = NULL,
         backup_email_verified = ${this.db.dialect === 'postgres' ? 'FALSE' : '0'},
         backup_email_verified_at = NULL,
         updated_at = ${phAt(this.db.dialect, 2)}
       WHERE id = ${phAt(this.db.dialect, 3)}`,
      [tombstoneEmail, at.toISOString(), at.toISOString(), userId],
    );
  }

  /** 宽限期已过、尚未清除的账号（启动清理用） */
  async findExpiredDeleted(cutoff: Date): Promise<UserRow[]> {
    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users
       WHERE deleted_at IS NOT NULL
         AND purged_at IS NULL
         AND deleted_at <= ${phAt(this.db.dialect, 0)}
       ORDER BY deleted_at ASC`,
      [cutoff.toISOString()],
    );
    return rows.map(mapUserRow);
  }

  // ---- 0003：用户名模式 ----

  /** 按备用邮箱精确查找（大小写不敏感，与主邮箱口径一致） */
  async findByBackupEmail(email: string): Promise<UserRow | null> {
    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users
       WHERE lower(backup_email) = ${phAt(this.db.dialect, 0)}`,
      [email.toLowerCase()],
    );
    return rows[0] ? mapUserRow(rows[0]) : null;
  }

  /**
   * 首次确定模式（存量多角色用户登录后选择保留 ID 时调用）。
   *
   * `profile_mode_decided_at` 用 COALESCE 保护：重复调用不会覆盖首次决定的时间点
   * —— 那个时间点是「用户何时被告知并接受了这套规则」的唯一记录，审计价值在此。
   */
  async decideMode(userId: string, mode: ProfileMode, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET profile_mode = ${phAt(this.db.dialect, 0)},
         profile_mode_decided_at = COALESCE(profile_mode_decided_at, ${phAt(this.db.dialect, 1)}),
         mode_changed_at = ${phAt(this.db.dialect, 2)},
         updated_at = ${phAt(this.db.dialect, 3)}
       WHERE id = ${phAt(this.db.dialect, 4)}`,
      [mode, at.toISOString(), at.toISOString(), at.toISOString(), userId],
    );
  }

  /** 切换模式（单 <-> 多）。不改 decided_at：它记录的是「首次决定」，不该被覆盖 */
  async setProfileMode(
    userId: string,
    mode: ProfileMode,
    at: Date,
  ): Promise<void> {
    await this.db.run(
      `UPDATE users SET profile_mode = ${phAt(this.db.dialect, 0)},
         mode_changed_at = ${phAt(this.db.dialect, 1)},
         updated_at = ${phAt(this.db.dialect, 2)}
       WHERE id = ${phAt(this.db.dialect, 3)}`,
      [mode, at.toISOString(), at.toISOString(), userId],
    );
  }

  // ---- P5 第十一批：全局用户名模式 ----
  // 模式改为全站统一（PROFILE_MODE 设置），每用户的 profile_mode 列退化为
  // 「全局值的同步副本」—— 服务层状态机仍只读它，切换时全量刷平即可。

  /** 全量同步副本：所有未注销用户的 profile_mode 刷成全局值 */
  async syncProfileModeForAll(mode: ProfileMode, at: Date): Promise<void> {
    const iso = at.toISOString();
    await this.db.run(
      `UPDATE users SET profile_mode = ${phAt(this.db.dialect, 0)},
         mode_changed_at = ${phAt(this.db.dialect, 1)},
         updated_at = ${phAt(this.db.dialect, 2)}
       WHERE deleted_at IS NULL`,
      [mode, iso, iso],
    );
  }

  /**
   * 把「名下有多个使用中角色」的用户标回待选择态（decided_at = NULL）。
   *
   * 全局切到 single 时调用：这些账号下次进个人中心会强制弹窗选保留 ID，
   * 选前一切写操作被既有状态机拦成 409。≤1 个可用角色的账号不受影响。
   */
  async markMultiActiveUndecided(at: Date): Promise<void> {
    const iso = at.toISOString();
    await this.db.run(
      `UPDATE users SET profile_mode_decided_at = NULL,
         updated_at = ${phAt(this.db.dialect, 0)}
       WHERE deleted_at IS NULL AND id IN (
         SELECT user_id FROM profiles WHERE status = 'active'
         GROUP BY user_id HAVING COUNT(*) > 1
       )`,
      [iso],
    );
  }

  /** 全局模式切换影响面统计（确认弹窗展示用） */
  async countProfileModeStats(): Promise<{
    totalUsers: number;
    multiActiveUsers: number;
    undecidedUsers: number;
  }> {
    const num = (rows: Record<string, unknown>[]): number =>
      Number(rows[0]?.['c'] ?? 0);
    const total = await this.db.query<Record<string, unknown>>(
      'SELECT COUNT(*) AS c FROM users WHERE deleted_at IS NULL',
    );
    const multiActive = await this.db.query<Record<string, unknown>>(
      `SELECT COUNT(*) AS c FROM (
         SELECT p.user_id FROM profiles p
         JOIN users u ON u.id = p.user_id AND u.deleted_at IS NULL
         WHERE p.status = 'active'
         GROUP BY p.user_id HAVING COUNT(*) > 1
       ) t`,
    );
    const undecided = await this.db.query<Record<string, unknown>>(
      `SELECT COUNT(*) AS c FROM users
       WHERE deleted_at IS NULL AND profile_mode_decided_at IS NULL`,
    );
    return {
      totalUsers: num(total),
      multiActiveUsers: num(multiActive),
      undecidedUsers: num(undecided),
    };
  }

  // ---- 0003：备用邮箱（兜底）----

  /**
   * 写入备用邮箱地址，**并强制回到未验证**。
   *
   * 这不是可以省的一步：若沿用上一次的 verified 标志，用户把备用邮箱从 A 改成 B
   * 后，B 会在没收到任何信件的情况下直接获得「已验证」身份，兜底邮箱就等于可以被
   * 任意改写 —— 而它的用途恰恰是「主邮箱失效时的救援通道」。
   */
  async setBackupEmail(userId: string, email: string, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET backup_email = ${phAt(this.db.dialect, 0)},
         backup_email_verified = ${this.db.dialect === 'postgres' ? 'FALSE' : '0'},
         backup_email_verified_at = NULL,
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [email.toLowerCase(), at.toISOString(), userId],
    );
  }

  /** 置备用邮箱验证状态；verified=false 时清掉 verified_at */
  async markBackupEmailVerified(
    userId: string,
    verified: boolean,
    at: Date,
  ): Promise<void> {
    await this.db.run(
      `UPDATE users SET backup_email_verified = ${phAt(this.db.dialect, 0)},
         backup_email_verified_at = ${phAt(this.db.dialect, 1)},
         updated_at = ${phAt(this.db.dialect, 2)}
       WHERE id = ${phAt(this.db.dialect, 3)}`,
      [
        this.db.dialect === 'postgres' ? verified : verified ? 1 : 0,
        verified ? at.toISOString() : null,
        at.toISOString(),
        userId,
      ],
    );
  }

  /** 解除备用邮箱绑定（用户主动移除；未验证的绑定也走这条清理） */
  async clearBackupEmail(userId: string, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET backup_email = NULL,
         backup_email_verified = ${this.db.dialect === 'postgres' ? 'FALSE' : '0'},
         backup_email_verified_at = NULL,
         updated_at = ${phAt(this.db.dialect, 0)}
       WHERE id = ${phAt(this.db.dialect, 1)}`,
      [at.toISOString(), userId],
    );
  }

  /**
   * 改主邮箱（邮箱变更流程收尾时调用）。
   *
   * 新地址在同一个流程里已由 verify 令牌证明归属，故一并把 `email_verified` 置真
   * —— 否则用户改完邮箱会突然变成「未验证」而在开启邮箱验证的站点上登不进去，
   * 这是纯粹的自我锁死，没有任何安全收益。
   */
  async updateEmail(userId: string, email: string, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET email = ${phAt(this.db.dialect, 0)},
         email_verified = ${this.db.dialect === 'postgres' ? 'TRUE' : '1'},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [email.toLowerCase(), at.toISOString(), userId],
    );
  }
}
