import type { DatabaseConnection } from '../types.js';
import { phAt, toBoolean, toIso } from '../db/rows.js';
import type { UserRole } from './tokenRepository.js';

/**
 * users 表 repository。
 *
 * user_uid 分配策略（schema/sqlite/0001_init.sql 头注）：
 * - PostgreSQL：`GENERATED BY DEFAULT AS IDENTITY`，插入省略该列由序列分配
 * - SQLite：应用层在插入事务内 MAX(user_uid)+1（单写者场景）
 * 两种方言下该方法都必须在调用方事务内执行（IdentityService 负责）。
 */

export interface UserRow {
  id: string;
  userUid: number;
  email: string;
  passwordHash: string;
  role: UserRole;
  isActive: boolean;
  emailVerified: boolean;
  bannedUntil: string | null;
  banPermanent: boolean;
  banReason: string | null;
  createdAt: string;
  updatedAt: string;
  lastLoginAt: string | null;
  /** 非空 = 已注销，处于可恢复宽限期（见 0002_account_lifecycle.sql） */
  deletedAt: string | null;
  /** 非空 = 宽限期已过、个人数据已清除；行保留以占住 user_uid（UID 永不复用） */
  purgedAt: string | null;
}

export interface NewUserRow {
  /** 应用层生成（uuidv4 小写带连字符） */
  id: string;
  /** 必须已规范化为小写 */
  email: string;
  passwordHash: string;
  role: UserRole;
  now: Date;
}

const USER_COLUMNS =
  'id, user_uid, email, password_hash, role, is_active, email_verified, ' +
  'banned_until, ban_permanent, ban_reason, created_at, updated_at, last_login_at, ' +
  'deleted_at, purged_at';

function mapUserRow(raw: Record<string, unknown>): UserRow {
  return {
    id: raw['id'] as string,
    userUid: Number(raw['user_uid']),
    email: raw['email'] as string,
    passwordHash: raw['password_hash'] as string,
    role: raw['role'] as UserRole,
    isActive: toBoolean(raw['is_active']),
    emailVerified: toBoolean(raw['email_verified']),
    bannedUntil: toIso(raw['banned_until']),
    banPermanent: toBoolean(raw['ban_permanent']),
    banReason: (raw['ban_reason'] as string | null) ?? null,
    createdAt: toIso(raw['created_at'])!,
    updatedAt: toIso(raw['updated_at'])!,
    lastLoginAt: toIso(raw['last_login_at']),
    deletedAt: toIso(raw['deleted_at']),
    purgedAt: toIso(raw['purged_at']),
  };
}

export class UserRepository {
  constructor(private readonly db: DatabaseConnection) {}

  /** 插入用户，返回分配到的 user_uid */
  async insert(user: NewUserRow): Promise<number> {
    const now = user.now.toISOString();

    if (this.db.dialect === 'postgres') {
      const rows = await this.db.query<Record<string, unknown>>(
        `INSERT INTO users (id, email, password_hash, role, is_active,
           email_verified, ban_permanent, created_at, updated_at)
         VALUES ($1, $2, $3, $4, TRUE, FALSE, FALSE, $5, $5)
         RETURNING user_uid`,
        [user.id, user.email, user.passwordHash, user.role, now],
      );
      return Number(rows[0]!['user_uid']);
    }

    // SQLite：同一事务内 MAX+1（见文件头注）
    const uidRows = await this.db.query<Record<string, unknown>>(
      'SELECT COALESCE(MAX(user_uid), 0) + 1 AS next_uid FROM users',
    );
    const userUid = Number(uidRows[0]!['next_uid']);
    await this.db.run(
      `INSERT INTO users (id, user_uid, email, password_hash, role, is_active,
         email_verified, ban_permanent, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, 1, 0, 0, ?, ?)`,
      [user.id, userUid, user.email, user.passwordHash, user.role, now, now],
    );
    return userUid;
  }

  async findByEmail(email: string): Promise<UserRow | null> {
    // email 唯一索引按 lower(email) 建立应用层不再依赖大小写形式
    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users WHERE lower(email) = ${phAt(this.db.dialect, 0)}`,
      [email.toLowerCase()],
    );
    return rows[0] ? mapUserRow(rows[0]) : null;
  }

  async findById(id: string): Promise<UserRow | null> {
    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users WHERE id = ${phAt(this.db.dialect, 0)}`,
      [id],
    );
    return rows[0] ? mapUserRow(rows[0]) : null;
  }

  async updateLastLogin(userId: string, at: Date): Promise<void> {
    // 注意：占位符下标不可重复（SQLite 每个 ? 都需要绑定值，PG 的 $n 重复只算一个）
    await this.db.run(
      `UPDATE users SET last_login_at = ${phAt(this.db.dialect, 0)},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [at.toISOString(), at.toISOString(), userId],
    );
  }

  /** 管理员用户列表（email 模糊搜索 + 分页），按 user_uid 升序 */
  async listUsers(options: {
    offset: number;
    limit: number;
    search?: string;
  }): Promise<{ rows: UserRow[]; total: number }> {
    const { offset, limit, search } = options;
    const like = search ? `%${search.toLowerCase()}%` : null;
    const searchClause = like
      ? ` WHERE lower(email) LIKE ${phAt(this.db.dialect, 0)}`
      : '';

    const countRows = await this.db.query<Record<string, unknown>>(
      `SELECT COUNT(*) AS total FROM users${searchClause}`,
      like ? [like] : [],
    );
    const total = Number(countRows[0]!['total']);

    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users${searchClause}
       ORDER BY user_uid ASC
       LIMIT ${phAt(this.db.dialect, like ? 1 : 0)}
       OFFSET ${phAt(this.db.dialect, like ? 2 : 1)}`,
      like ? [like, limit, offset] : [limit, offset],
    );
    return { rows: rows.map(mapUserRow), total };
  }

  /** 管理员更新用户管理字段（角色/封禁/激活），仅写传入的字段 */
  async updateAdminFields(
    userId: string,
    fields: {
      role?: UserRole;
      isActive?: boolean;
      bannedUntil?: string | null;
      banPermanent?: boolean;
      banReason?: string | null;
    },
    now: Date,
  ): Promise<void> {
    const sets: string[] = [];
    const values: unknown[] = [];
    let i = 0;
    if (fields.role !== undefined) {
      sets.push(`role = ${phAt(this.db.dialect, i++)}`);
      values.push(fields.role);
    }
    if (fields.isActive !== undefined) {
      sets.push(`is_active = ${phAt(this.db.dialect, i++)}`);
      values.push(this.db.dialect === 'postgres' ? fields.isActive : fields.isActive ? 1 : 0);
    }
    if (fields.bannedUntil !== undefined) {
      sets.push(`banned_until = ${phAt(this.db.dialect, i++)}`);
      values.push(fields.bannedUntil);
    }
    if (fields.banPermanent !== undefined) {
      sets.push(`ban_permanent = ${phAt(this.db.dialect, i++)}`);
      values.push(this.db.dialect === 'postgres' ? fields.banPermanent : fields.banPermanent ? 1 : 0);
    }
    if (fields.banReason !== undefined) {
      sets.push(`ban_reason = ${phAt(this.db.dialect, i++)}`);
      values.push(fields.banReason);
    }
    sets.push(`updated_at = ${phAt(this.db.dialect, i++)}`);
    values.push(now.toISOString());
    values.push(userId);

    await this.db.run(
      `UPDATE users SET ${sets.join(', ')} WHERE id = ${phAt(this.db.dialect, i++)}`,
      values,
    );
  }

  // ---- 账号生命周期（改密 / 注销 / 恢复 / 到期清除）----

  async updatePassword(
    userId: string,
    passwordHash: string,
    at: Date,
  ): Promise<void> {
    await this.db.run(
      `UPDATE users SET password_hash = ${phAt(this.db.dialect, 0)},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [passwordHash, at.toISOString(), userId],
    );
  }

  /** 注销：置 deleted_at，进入可恢复宽限期 */
  async markDeleted(userId: string, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET deleted_at = ${phAt(this.db.dialect, 0)},
         updated_at = ${phAt(this.db.dialect, 1)}
       WHERE id = ${phAt(this.db.dialect, 2)}`,
      [at.toISOString(), at.toISOString(), userId],
    );
  }

  /** 恢复：清 deleted_at，账号回到正常状态 */
  async clearDeleted(userId: string, at: Date): Promise<void> {
    await this.db.run(
      `UPDATE users SET deleted_at = NULL,
         updated_at = ${phAt(this.db.dialect, 0)}
       WHERE id = ${phAt(this.db.dialect, 1)}`,
      [at.toISOString(), userId],
    );
  }

  /**
   * 宽限期到期清除：邮箱改墓碑值（释放原邮箱给新注册）、密码清空、停用，
   * 并写 purged_at。**行本身保留**——SQLite 的 user_uid 由 MAX(uid)+1 分配，
   * 删行会导致 UID 被后续注册复用，而 UID 要求永不复用。
   */
  async purgeUser(
    userId: string,
    tombstoneEmail: string,
    at: Date,
  ): Promise<void> {
    await this.db.run(
      `UPDATE users SET email = ${phAt(this.db.dialect, 0)},
         password_hash = '',
         is_active = ${this.db.dialect === 'postgres' ? 'FALSE' : '0'},
         deleted_at = NULL,
         purged_at = ${phAt(this.db.dialect, 1)},
         updated_at = ${phAt(this.db.dialect, 2)}
       WHERE id = ${phAt(this.db.dialect, 3)}`,
      [tombstoneEmail, at.toISOString(), at.toISOString(), userId],
    );
  }

  /** 宽限期已过、尚未清除的账号（启动清理用） */
  async findExpiredDeleted(cutoff: Date): Promise<UserRow[]> {
    const rows = await this.db.query<Record<string, unknown>>(
      `SELECT ${USER_COLUMNS} FROM users
       WHERE deleted_at IS NOT NULL
         AND purged_at IS NULL
         AND deleted_at <= ${phAt(this.db.dialect, 0)}
       ORDER BY deleted_at ASC`,
      [cutoff.toISOString()],
    );
    return rows.map(mapUserRow);
  }
}
