-- ============================================================================
-- MSCTS canonical schema · 0001_init · PostgreSQL
-- 草案 v1（2026-09-20，待评审，未在任何数据库上执行）
--
-- 约定：
--   1. 所有主键为 UUID（小写带连字符），由应用层生成
--   2. 所有时间为 TIMESTAMPTZ，由应用层写入 UTC 值；
--      业务 SQL 与 DDL 中禁止使用数据库时间函数（无 DEFAULT CURRENT_TIMESTAMP）
--   3. 枚举统一用 TEXT + CHECK，不使用数据库原生 ENUM
--   4. 外键删除行为全部显式声明
--   5. 本文件为 canonical；schema/sqlite/0001_init.sql 必须与之结构等价，
--      等价性由迁移 smoke test（蓝图任务 2）强制保证
--   6. 迁移文件内禁止 BEGIN/COMMIT 等事务控制语句，事务边界由迁移 runner 拥有
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 1. 身份与权限
-- ----------------------------------------------------------------------------

-- 站点用户（与 Minecraft Profile 分离）
-- role 为唯一权限事实来源；level(0/1/2) 仅作为旧 API 的兼容映射
CREATE TABLE users (
  id             UUID PRIMARY KEY,
  user_uid       BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  email          TEXT NOT NULL,                  -- 应用层保证小写规范化
  password_hash  TEXT NOT NULL,                  -- bcrypt
  role           TEXT NOT NULL DEFAULT 'user'
                   CHECK (role IN ('user', 'admin', 'super_admin')),
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  banned_until   TIMESTAMPTZ,                    -- 临时封禁截止；NULL = 未临时封禁
  ban_permanent  BOOLEAN NOT NULL DEFAULT FALSE, -- 永久封禁
  ban_reason     TEXT,
  created_at     TIMESTAMPTZ NOT NULL,
  updated_at     TIMESTAMPTZ NOT NULL,
  last_login_at  TIMESTAMPTZ,
  CONSTRAINT users_ban_shape
    CHECK (NOT (ban_permanent AND banned_until IS NOT NULL))
);

-- email 唯一性按小写形式约束
CREATE UNIQUE INDEX users_email_lower_uidx ON users (lower(email));

-- Minecraft 角色（对外可见的游戏身份）
CREATE TABLE profiles (
  id              UUID PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name            TEXT NOT NULL UNIQUE,          -- 3-16 位 [A-Za-z0-9_]，应用层校验
  name_changed_at TIMESTAMPTZ NOT NULL,          -- 改名 30 天冷却基准
  created_at      TIMESTAMPTZ NOT NULL,
  updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX profiles_user_idx ON profiles (user_id);

-- ----------------------------------------------------------------------------
-- 2. 文件对象与素材
-- ----------------------------------------------------------------------------

-- 不可变文件对象（按 sha256 全局去重；数据库只存 object key，不存完整 URL）
CREATE TABLE blobs (
  id           UUID PRIMARY KEY,
  sha256       TEXT NOT NULL UNIQUE,             -- 小写 hex
  storage_key  TEXT NOT NULL UNIQUE,             -- 内容寻址 key，如 blobs/ab/ab12….png
  content_type TEXT NOT NULL,
  byte_size    BIGINT NOT NULL,
  width        INTEGER NOT NULL,
  height       INTEGER NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL
);

-- 素材（皮肤/披风统一，kind 区分）
CREATE TABLE assets (
  id              UUID PRIMARY KEY,
  owner_user_id   UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind            TEXT NOT NULL CHECK (kind IN ('skin', 'cape')),
  blob_id         UUID NOT NULL REFERENCES blobs (id),  -- 默认 RESTRICT：被引用的 blob 不可删
  model_type      TEXT,                                  -- 仅皮肤：default | slim
  name            TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  license         TEXT NOT NULL DEFAULT 'CC0',
  visibility      TEXT NOT NULL DEFAULT 'private'
                    CHECK (visibility IN ('private', 'public')),
  download_policy TEXT NOT NULL DEFAULT 'owner_only'
                    CHECK (download_policy IN ('owner_only', 'public')),
  review_status   TEXT NOT NULL DEFAULT 'pending'
                    CHECK (review_status IN ('pending', 'approved', 'rejected')),
  ai_generated    BOOLEAN NOT NULL DEFAULT FALSE,
  admin_warning   TEXT,
  view_count      BIGINT NOT NULL DEFAULT 0,
  download_count  BIGINT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL,
  updated_at      TIMESTAMPTZ NOT NULL,
  CONSTRAINT assets_model_shape CHECK (
    (kind = 'skin' AND model_type IN ('default', 'slim'))
    OR (kind = 'cape' AND model_type IS NULL)
  )
);

CREATE INDEX assets_owner_idx ON assets (owner_user_id);
CREATE INDEX assets_blob_idx ON assets (blob_id);
-- 公开库查询路径
CREATE INDEX assets_library_idx
  ON assets (kind, visibility, review_status, created_at);

-- 角色当前绑定（每角色每槽位最多一条）
-- slot 与 assets.kind 的一致性由应用服务保证（CHECK 无法跨表表达，写入测试覆盖）
CREATE TABLE profile_assets (
  id          UUID PRIMARY KEY,
  profile_id  UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  asset_id    UUID NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
  slot        TEXT NOT NULL CHECK (slot IN ('skin', 'cape')),
  assigned_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT profile_assets_unique_slot UNIQUE (profile_id, slot)
);

-- 收藏（皮肤/披风统一；"发布者默认收藏"是领域服务规则，不在 schema 层表达）
CREATE TABLE favorites (
  user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  asset_id   UUID NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, asset_id)
);

CREATE INDEX favorites_asset_idx ON favorites (asset_id);

-- 审核流水（assets.review_status 为当前态，本表为历史）
CREATE TABLE asset_reviews (
  id               UUID PRIMARY KEY,
  asset_id         UUID NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
  reviewer_user_id UUID REFERENCES users (id) ON DELETE SET NULL,  -- 审核人删除账号时匿名化
  status           TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
  reason           TEXT,
  created_at       TIMESTAMPTZ NOT NULL
);

CREATE INDEX asset_reviews_asset_idx ON asset_reviews (asset_id);

-- ----------------------------------------------------------------------------
-- 3. 令牌与会话
-- ----------------------------------------------------------------------------

-- 统一令牌表（web / yggdrasil 共用结构；数据库不存明文）
CREATE TABLE tokens (
  id           UUID PRIMARY KEY,
  token_hash   TEXT NOT NULL UNIQUE,             -- sha256(明文 token) 小写 hex
  token_type   TEXT NOT NULL CHECK (token_type IN ('web', 'yggdrasil')),
  client_token TEXT,                             -- Yggdrasil clientToken 原样回显（非凭据）
  user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  profile_id   UUID REFERENCES profiles (id) ON DELETE SET NULL,  -- selectedProfile 绑定
  issued_at    TIMESTAMPTZ NOT NULL,
  expires_at   TIMESTAMPTZ NOT NULL,
  last_used_at TIMESTAMPTZ,
  revoked_at   TIMESTAMPTZ,
  CONSTRAINT tokens_expiry_shape CHECK (expires_at > issued_at)
);

CREATE INDEX tokens_user_idx ON tokens (user_id, token_type);

-- Minecraft join / hasJoined 短会话（TTL 约 30-60 秒；过期由清理任务删除）
CREATE TABLE minecraft_sessions (
  id         UUID PRIMARY KEY,
  token_id   UUID NOT NULL REFERENCES tokens (id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  server_id  TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX minecraft_sessions_lookup_idx ON minecraft_sessions (server_id, profile_id);
CREATE INDEX minecraft_sessions_expiry_idx ON minecraft_sessions (expires_at);

-- Web 登录会话登记（审计与"登出所有设备"）
CREATE TABLE login_sessions (
  id           UUID PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_id     UUID NOT NULL REFERENCES tokens (id) ON DELETE CASCADE,
  ip           TEXT,
  user_agent   TEXT,
  created_at   TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ
);

CREATE INDEX login_sessions_user_idx ON login_sessions (user_id);

-- ----------------------------------------------------------------------------
-- 4. 账号辅助流程
-- ----------------------------------------------------------------------------

CREATE TABLE email_verification_tokens (
  id         UUID PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ
);

CREATE INDEX email_verification_tokens_user_idx ON email_verification_tokens (user_id);

CREATE TABLE password_reset_tokens (
  id         UUID PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ
);

CREATE INDEX password_reset_tokens_user_idx ON password_reset_tokens (user_id);

CREATE TABLE oauth_accounts (
  id                  UUID PRIMARY KEY,
  user_id             UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  provider            TEXT NOT NULL CHECK (provider IN ('github', 'microsoft')),
  provider_account_id TEXT NOT NULL,
  created_at          TIMESTAMPTZ NOT NULL,
  CONSTRAINT oauth_accounts_provider_uid UNIQUE (provider, provider_account_id)
);

CREATE INDEX oauth_accounts_user_idx ON oauth_accounts (user_id);

-- ----------------------------------------------------------------------------
-- 5. 黑名单与系统设置
-- ----------------------------------------------------------------------------

CREATE TABLE blacklist_entries (
  id         UUID PRIMARY KEY,
  kind       TEXT NOT NULL CHECK (kind IN ('email', 'ip')),
  value      TEXT NOT NULL,
  reason     TEXT,
  created_by UUID REFERENCES users (id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ,                       -- NULL = 永久
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT blacklist_entries_uid UNIQUE (kind, value)
);

CREATE TABLE system_settings (
  key        TEXT PRIMARY KEY,
  value      JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
